version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key
    depends_on:
      - docker-setup

  docker-setup:
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["sh", "-c", "docker pull python:3.11-slim && exit 0"]
